[project]
name = "to-feature-store"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.9"
dependencies = [
    "hopsworks>=4.1.3",
    "loguru>=0.7.3",
    "pyarrow>=19.0.1",
    "quixstreams>=3.11.0",
]
