[project]
name = "demand-features"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.9"
dependencies = [
    "holidays>=0.68",
    "loguru>=0.7.3",
    "numpy>=2.2.3",
    "quixstreams>=3.10.0",
]
